### ISSUE TITLE
[FACEX] custom data_transform is always overwritten by facex

### ISSUE THREAD

**Issue by elmokhtar-mohamedmoussa-idnow** [mammoth-eu/mammoth-commons#13]
Hello,

When testing the faceX module from the commons catalogue, user can specify a custom dataset with **custom data transformation** (see :  [https://github.com/mammoth-eu/mammoth-commons/blob/dev/tests/test_tc6_facex.py#L24](url) )
However, the custom data transformation will be always ignored since its is **overwritten in [facextool](https://github.com/gsarridis/faceX/)** : [https://github.com/gsarridis/faceX/blob/main/facex/dataset.py#L269](url).
This can be an issue obviously, when testing with custom models.

**Comment by gsarridis** [comment]
Hi Elmokhtar,  

Thank you for pointing out the issue!

I've updated the facextool library accordingly. Please try upgrading it by running:

`pip install --upgrade facextool`

Let me know if everything works as expected!

**Comment by maniospas** [comment]
Pinging for an update @elmokhtar-mohamedmoussa-idnow .

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
Hi manios, 
This issue is indeed solved. thanks a lot @gsarridis for the support.
