### ISSUE TITLE
Running multiple models and comparing them

### ISSUE THREAD

**Issue by sudhang** [mammoth-eu/mammoth-commons#15]
Hello.

One of my requirements is to run multiple models (specifically, an unfair and a fair one) for ranking researchers, and comparing them by displaying a visualization.  For now, I am doing this by putting this comparison and visualization code in the test code.  However, I am not sure if that fits in with the expectations of this framework.  Is there a better way to do this?  Naturally, we would like to follow what the framework expects from us.

**Comment by sudhang** [comment]
UPDATE: to make it more concrete, the framework seems to require that each "metric" be a small report marked up in HTML or markdown format.  However, in order to achieve what I said above, I could:
1. have a metric that implements both the fair and unfair metrics
2. performs the comparisons
3. does the visualisations
4. put it into the HTML output
That would be a single metric which does all of the above, rather than multiple metrics.  This is possible, but I wonder if this goes against the intent of the framework.

**Comment by maniospas** [comment]
Hello, and thanks fro the question.

Properly comparing fair vs unfair currently depends on whether the main [toolkit](https://github.com/mammoth-eu/mammoth-toolkit-releases/issues) will implement viewing the outputs of multiple that one can compare runs side-by-side. This was something discussed at some point, but I am not sure that there will be time to implement it. Tagging @georgiosn here in case he can answer.

To play it safe, and given that this functionality is not currently supported, I am suggesting you do as you already mention @sudhang and pack both in one report. This, given my understanding that only one algorithm is given as input (if there is a fair version and a normal version of an algorithm, you inevitably need to have two different metrics). 

By the way, the intent is for each "metric" to be a fully fleshed HTML page with multiple results (we probably need to rename this concept). For example this is the output of one of the metric modules, where you can see that there is a lot of stuff packed in there.

![{BC0BB7F2-E27D-4543-9AF5-DFA7A5107112}](https://github.com/user-attachments/assets/8aefdadf-6928-4d6c-b1b8-78d2ee88a8f3)

**Comment by sudhang** [comment]
Hi @maniospas : thanks for the clarification.  Then it's clear;  One can make it work as a "compound" report in my case with fair and unfair rankers shown side-by-side

**Comment by sudhang** [comment]
Closing the issue, and proceeding to group the fair/unfair version of the researcher ranking into a single report.
