### ISSUE TITLE
Warning from the multisoc library

### ISSUE THREAD

**Issue by maniospas** [mammoth-eu/mammoth-commons#27]
Hi,
I am in the middle for enabling and testing all graph pipelines for the demonstrator, and get this error from the `multisoc` library in Python 3.10. This should ideally not occur.

```
C:\Users\manio\PycharmProjects\mammoth-commons\venv_test\lib\site-packages\multisoc\infer\inference.py:47: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  att_counts = [link_count.groupby(level=i, axis=1, sort=False).sum().groupby(level=i, axis=0, sort=False).sum() for i in range(n_attributes)]
```

**Comment by MauritzNiklas** [comment]
Thanks for noticing. It's a Future Warning, so it won't influence how the code works, but I'm on it to solve it. I'll let you know once I've updated the package

**Comment by MauritzNiklas** [comment]
I updated the multisoc package to version 0.1.1 which should include the fix
Let me know if the problem persists

**Comment by maniospas** [comment]
Thanks a lot!
This spammed the console screen with 100s of warnings, which made debugging harder than needed (and would also give a bad impression if you plan to show things in the demonstrator).
It has indeed been fixed.
