### ISSUE TITLE
error in demonstrator at step 3 with onnx_ensemble

### ISSUE THREAD

**Issue by arjunroyihrpa** [mammoth-eu/mammoth-commons#33]
<img width="1167" alt="Screenshot 2024-11-01 at 12 24 42" src="https://github.com/user-attachments/assets/50b5edb7-2ce6-4342-84fc-b30ede732acd">
<img width="1221" alt="Screenshot 2024-11-01 at 12 29 59" src="https://github.com/user-attachments/assets/e6441c54-07b4-4faa-a6a5-583c07b77a3f">

**Comment by maniospas** [comment]
Hi, 
since there are no data submitted I fixed the method to the point that it does not create these kinds of errors.
You still need sensitive attributes for fairness analysis.
For me, it still creates an error that I am not inputting the same data dimensions as the ones the model has been trained on. 

Please check if it works on your end. If so, close this issue.

**Comment by maniospas** [comment]
To clarify, if I follow the workshop template, I get this:

![image](https://github.com/user-attachments/assets/c553b029-14ae-48f9-a0ab-3010fe2aa9aa)

The stack trace is this:

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: X for the following indices
 index: 1 Got: 33 Expected: 23
 Please fix either the inputs/outputs or the model.
Traceback (most recent call last):
  File "/home/maniospas/Documents/mammoth-commons/demonstrator/backend/handlers/handle_fairness_analysis.py", line 93, in handle_fairness_analysis_post
    result = name_to_runnable[selected_method](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maniospas/Documents/mammoth-commons/catalogue/metrics/interactive_report.py", line 50, in interactive_report
    predictions = model.predict(dataset, sensitive)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maniospas/Documents/mammoth-commons/mammoth/models/onnx_ensemble.py", line 20, in predict
    pred = sum(
           ^^^^
  File "/home/maniospas/Documents/mammoth-commons/mammoth/models/onnx_ensemble.py", line 21, in <genexpr>
    (estimator.predict(X, []) == classes).T * w
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maniospas/Documents/mammoth-commons/mammoth/models/onnx.py", line 18, in predict
    return sess.run([label_name], {input_name: x.astype(self.np_type)})[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maniospas/Documents/mammoth-commons/venv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: X for the following indices
 index: 1 Got: 33 Expected: 23
 Please fix either the inputs/outputs or the model.
 ```

**Comment by arjunroyihrpa** [comment]
Hi, 
internally I also debugged to this point, and no quick fix for this error. Because, the to_feature function transforms the data to a shape that it does not understand. For a start, sensitive attributes are part of input (which for most of ML also is a strict no). However, I still tried moving beyond this step by force, but then I ran into another error where predict function now requires sensitive attributes. You need to fix this in the onnx.py file predictor. Basically the to_features() function if not called there it is best. If you need this transformation to exist, let me know, I will make the changes inside the onnx_ensemble file, to make it work. 

All these errors are result of a change inside the code (which was not informed to me) from the one I initially provided.

**Comment by arjunroyihrpa** [comment]
anyways just to inform, I am resolving this in my local version. So the demonstrator from my local machine should work. Will later discuss how to integrate to the global release.

**Comment by arjunroyihrpa** [comment]
Also modification in fairness_analysis.html page is needed

// Populate dropdown options with sensitive attributes
        sensitiveAttributes.forEach(attribute => {
            const option = document.createElement('option');
            option.value = attribute;
            option.textContent = attribute;
            if (attribute === prefilledValue) {
                option.selected = true;  // Pre-select if it matches the prefilled value
            }
            select.appendChild(option);
        });

the sensitive attribute drop down menu must take values (attributes) from datapoints not to be used for predictions

**Comment by arjunroyihrpa** [comment]
Locally I resolved all the issues and can run it for generating cards. I mainly modified the csv_loader(). However, for interactive reports I am getting this error:

Error during fairness analysis
unsupported operand type(s) for +: 'int' and 'str'
